# Generated by Django 4.1.2 on 2022-10-23 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("BookExchange", "0002_alter_textbooks_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(max_length=254, unique=True),
        ),
    ]
