# Generated by Django 3.2.15 on 2022-10-23 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooks',
            name='creator',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
