# Generated by Django 4.1.3 on 2022-11-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0005_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooks',
            name='classroom',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
