# Generated by Django 4.1.3 on 2022-11-04 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0006_textbooks_classroom'),
    ]

    operations = [
        migrations.AddField(
            model_name='textbooks',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
