# Generated by Django 4.1.3 on 2022-11-12 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0009_auto_20221111_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='textbooks',
            old_name='classroom',
            new_name='course',
        ),
        migrations.AddField(
            model_name='textbooks',
            name='instructor',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='favorites',
            field=models.ManyToManyField(related_name='favorited_by', to='BookExchange.textbooks'),
        ),
    ]
