# Generated by Django 4.1.3 on 2022-11-12 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0010_rename_classroom_textbooks_course_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooks',
            name='course',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='textbooks',
            name='instructor',
            field=models.CharField(default='', max_length=255),
        ),
    ]
