# Generated by Django 4.1.3 on 2022-11-25 08:04

from django.db import migrations
import isbn_field.fields
import isbn_field.validators


class Migration(migrations.Migration):

    dependencies = [
        ('BookExchange', '0014_profile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='textbooks',
            name='isbn',
            field=isbn_field.fields.ISBNField(max_length=28, validators=[isbn_field.validators.ISBNValidator], verbose_name='ISBN'),
        ),
    ]
